# Generated by Django 5.1.6 on 2025-03-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Peter', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(default='Peter Julius TextFieldstacio'),
            preserve_default=False,
        ),
    ]
